version: '2'
services:

  # 在1.4.3  msp文件的结构发生了变化，因此最好使用1.4.3以后的版本
  orderer.blockchainrealestate.com:
    container_name: orderer.blockchainrealestate.com
    image: hyperledger/fabric-orderer:1.4.4
    dns_search: . # 解决一些连接不上的问题
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0 # 服务暴露地址
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/config/genesis.block # 注入创世区块
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp # 证书相关
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
      - ORDERER_GENERAL_LISTENPORT=7050
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050 # 17050:7050
      - 8443:8443
    volumes:
      - ./config/genesis.block:/etc/hyperledger/config/genesis.block
      - ./crypto-config/ordererOrganizations/blockchainrealestate.com/orderers/orderer.blockchainrealestate.com/:/etc/hyperledger/orderer

  peer0.org0.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org0.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org0.blockchainrealestate.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer0.org0.blockchainrealestate.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org0.blockchainrealestate.com:7051
    ports:
      - 7051:7051 # grpc服务端口
      #- 7053:7053 # eventhub端口
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.blockchainrealestate.com/peers/peer0.org0.blockchainrealestate.com:/etc/hyperledger/peer
    # 所有peer节点都必须依赖order节点用于排序
    depends_on:
      - orderer.blockchainrealestate.com

  peer1.org0.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org0.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org0.blockchainrealestate.com
      - CORE_PEER_LOCALMSPID=Org0MSP
      - CORE_PEER_ADDRESS=peer1.org0.blockchainrealestate.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org0.blockchainrealestate.com:8051
    ports:
      - 17051:8051
      #- 17053:8053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org0.blockchainrealestate.com/peers/peer1.org0.blockchainrealestate.com:/etc/hyperledger/peer
    depends_on:
      - orderer.blockchainrealestate.com

  peer0.org1.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org1.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.blockchainrealestate.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.blockchainrealestate.com:9051
      # 在安装和实例化链码过程中节点需要相互通信，必须正确加上这个环境变量
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.blockchainrealestate.com:9051
    ports:
      - 27051:9051
      #- 27053:9053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.blockchainrealestate.com/peers/peer0.org1.blockchainrealestate.com:/etc/hyperledger/peer
    depends_on:
      - orderer.blockchainrealestate.com

  peer1.org1.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org1.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org1.blockchainrealestate.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.blockchainrealestate.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.blockchainrealestate.com:10051
    ports:
      - 37051:10051
      #- 37053:10053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.blockchainrealestate.com/peers/peer1.org1.blockchainrealestate.com:/etc/hyperledger/peer
    depends_on:
      - orderer.blockchainrealestate.com

  peer0.org2.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer0.org2.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.blockchainrealestate.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.blockchainrealestate.com:11051
      # 监听这个端口
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      # 必须配置这个环境变量才能被区块链浏览器读到
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.blockchainrealestate.com:11051
    ports:
      - 47051:11051
      #- 47053:11053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.blockchainrealestate.com/peers/peer0.org2.blockchainrealestate.com:/etc/hyperledger/peer
    depends_on:
      - orderer.blockchainrealestate.com

  peer1.org2.blockchainrealestate.com:
    extends:
      file: docker-compose-base.yaml
      service: peer-base
    container_name: peer1.org2.blockchainrealestate.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.org2.blockchainrealestate.com
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.blockchainrealestate.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org2.blockchainrealestate.com:12051
    ports:
      - 57051:12051
      #- 57053:12053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org2.blockchainrealestate.com/peers/peer1.org2.blockchainrealestate.com:/etc/hyperledger/peer
    depends_on:
      - orderer.blockchainrealestate.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.4
    dns_search: .
    tty: true
    environment:
      - GOPATH=/opt/gopath
      # CORE_LOGGING_LEVEL is no longer supported, please use the FABRIC_LOGGING_SPEC environment variable
      # - CORE_LOGGING_LEVEL=DEBUG fmy modified in 2021.09.12
      # - FABRIC_LOGGING_SPEC=DEBUG

      # Default logging levels are specified here.

      # Valid logging levels are case-insensitive strings chosen from

      #     CRITICAL | ERROR | WARNING | NOTICE | INFO | DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      # - FABRIC_LOGGING_SPEC=DEBUG   # 详细查询问题就使用debug
      - CORE_PEER_ID=cli
      # 测试修复区块链浏览器不显示的问题，改为peer0.org0进行测试
      # - CORE_PEER_ADDRESS=peer0.org1.blockchainrealestate.com:7051,根据configtx中的端口做修改
      - CORE_PEER_ADDRESS=peer0.org1.blockchainrealestate.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
      # - CORE_PEER_ADDRESS=peer0.org0.blockchainrealestate.com:7051
      # - CORE_PEER_LOCALMSPID=Org0MSP
      # 节点加入环境变量的路径问题主要就是这个(这个路径必须根据挂载路径做修改,作为环境变量是可以修改的)
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/users/Admin@org1.blockchainrealestate.com/msp
      
      # 不在cli容器中挂载 msp路径，在脚本中动态替换
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/org1.blockchainrealestate.com/users/Admin@org1.blockchainrealestate.com/msp
      # - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/org0.blockchainrealestate.com/users/Admin@org0.blockchainrealestate.com/msp
      # 进入容器显示的默认路径
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/
    command: /bin/bash
    volumes:
      - ./../chaincode:/opt/gopath/src/github.com/fmy1993/BCexplorer/chaincode # 链码路径注入
      - ./config:/etc/hyperledger/config # 区块相关信息存储路径(.block / .tx)
      # 这里只挂载了一个节点的MSP，为了能加入其他节点，修改挂载路径
      # - ./crypto-config/peerOrganizations/org1.blockchainrealestate.com/:/etc/hyperledger/peer
      - ./crypto-config/peerOrganizations/:/etc/hyperledger/peer